### PR TITLE
Fix checkm data setRoot command to work from command line.

### PR DESCRIPTION
**Pull request by ctb**
Briefly, with this patch, `checkm data setRoot <path>` will now correctly set the data root for checkm to `<path>`. Previously it would not respect `<path>` and would instead prompt for interactive output.

In particular, this causes problems with workflows that construct conda environments, because the workflow manager cannot automatically set the data location for a newly installed checkM via the command line.

NOTE: this is a PR into `python3_dev`.

More:

I've been bedeviled for years now by this minor issue, so I thought I'd set out to fix it! It was trickier than expected... The cause of the problem appears to be that the `DBManager` class is created on import of the `defaultValues` module, which happens before any argument parsing happens.

I made the following changes:
* added an explicit `initValues()` call to the DefaultValues object instead of having things depend on class variables;
* in main.py, intercepted the `data SetRoot` action before `initValues()`;
* intercepted the `setRoot` action in DBManager.__init__ before database was initialized;
* added an `os._exit` to get out of things without printing an error message.

It's a bit hacky but it seemed like the minimal set of changes needed to fix this, and I _think_ it works more generally. Happy to massage and updated as needed.

### CODE REVIEW

**Comment by ctb** [comment]
thanks!!

**Comment by dparks1134** [comment]
Thanks for submitting the fix. BTW, the python3_dev branch is not maintained or tested by myself. It has been put together by others. I have no reason to think it isn't 100% functional, but nobody is taking direct responsibility for testing it either. My efforts are focused on CheckM v2 which will by native Python 3.

**Comment by ctb** [comment]
ok, thx! is there a chance for a new v1 release that contains the python3_dev
branch? or should I backport this fix into master without python3 compat
if I want this fix to be available in conda?

**Comment by dparks1134** [comment]
Unfortunately, there is no plan to make a CheckM v1 based on the python3_dev branch since the changes are extensive and I don't currently have the resources to test them. I know others have had issues with the interactive setting of the data directory so if you wish to backport this to the master branch it would be much appreciated and I will issue a new release based on this change.

**Comment by dparks1134** [comment]
Thanks again for the PR. I have ported this to the master branch and am preparing a new release of CheckM that incorporates this change.

**Comment by ctb** [comment]
wow, thanks!

**Pull request merged**
