### PR TITLE
Set default location for checkm data

### PR DESCRIPTION
**Pull request by nickp60**
Hi CheckM folks!  Thanks for making a great tool!  I have a small request: can we make a default place for the database?  Requiring user input makes it tricky to install in a pipeline context (See  https://github.com/edgraham/BinSanity/issues/29, https://github.com/ISU-HPC/bamm-groopm-checkm/issues/1, https://github.com/nf-core/mag/issues/13).  The change I purpose here makes a dot directory in the users home folder -- no privilege issues that I know about, and complies with section 3.8.2 of the File Hierarchy Standard https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s08.html

While the changes in this PR only are for the data dir, having this would also be a nice place for putting the CONFIG_DATA file, as it seems like some users are running into permissions problems when using CheckM inside containers.  

I know you are working on CheckM 2.0, but if this is something you would consider, let me know how I could help make it happen!

Thanks again,

Nick

### CODE REVIEW

**Comment by dparks1134** [comment]
Hello Nick. I haven't look at your actual changes yet. Does it still support installing the CheckM data to a central location? At least some research labs setup CheckM by install the CheckM data to a shared data directory and then pointing the software to this. This means every user doesn't need to have a copy of the data and there is a single place where the data would need to be updated.

**Comment by nickp60** [comment]
Yes -- all this does is make the default ~/.checkm/ . If the install is in a central location, users/admins would just have to edit the `dataRoot` entry in DATA_CONFIG  to point to the centralized location.

**Comment by dparks1134** [comment]
Sorry for the slow reply. I'm hesitant to make changes to CheckM as it is working for most people. Can you not modify the DATA_CONFIG for your installation needs? The change in your PR would break the install script of anyone using the current setup from what I can tell.

**Comment by nickp60** [comment]
The issue I see is that requiring user input breaks automated installs, and it does so silently to that it hangs infinitely. Modifying DATA_CONFIG doesn't change that.  I don't think this change "breaks" anything, it just doesn't wait for a user to type in a location, defaulting instead to the FSH recommended location. If users on a shared machine need to, they could still modify DATA_CONFIG to point to the shared location of the database.

An alternate approach if you still want the script to take user input would be to have the main pipeline fail with an appropriate  exit code if the data directory hasn't be set up properly, rather than automatically calling the config command. At least that way if users have installed it as part of a pipeline, they will be made aware of what would need to happen. 

Ultimately, as you say, its only a issue for people trying to install the tool as part of a larger pipeline, where they wont be as familiar with the particular CheckM commands. Whatever you think is best, feel free to close this PR out!

**Comment by dparks1134** [comment]
I think I will leave CheckM as is and look to address these issue in CheckM v2. I know people have scripts for the current install situation where they are using some magic to force in the desired directory for the CheckM data and thus effectively bypassing the interactive prompt.

**Comment by dparks1134** [comment]
Hi Nick. I just accepted a pull request "Fix checkm data setRoot command to work from command line" by cbt into the python3_dev branch. This modifies CheckM so that the data path can be set with `checkm data setRoot <path>`. This is easier for me to accept since it doesn't change any of the current functionality. If this would resolve your concerns, I'd be happy to accept a PR on the master branch with the same changes.

**Comment by dparks1134** [comment]
I am preparing a new version of CheckM that I plan to release later today. It incorporates the PR by cbt that fixes the `checkm data setRoot <path>` issue.

**Comment by dparks1134** [comment]
Hi Nick. Version 1.0.16 implements the ~/.checkm default directory as you suggested. You will be happy to know the `checkm data setRoot` is no longer interactive.

**Comment by nickp60** [comment]
Hi @dparks1134 , so sorry for the late reply -- I was out of town and this got buried.   Thanks so much for looking into this, and thanks again for CheckM!

**Pull request closed without merging**
